### ISSUE TITLE
Possible to get working with Houdini 20.5.370

### ISSUE THREAD

**Issue by djdoogle123** [grabanton/lighter#3]
Hello I have followed your instructions and copy and pasted the libs file from the framework folder in Houdini to the destination folder of lighter, 

then I have renamed them according python 3.10 libs, python 3.11 libs.

but still no joy, any chance of a update or being able to get this working on later versions? 

regards 

Luke

**Comment by grabanton** [comment]
Asset was updated. It works with 20.5 now
